# Generated by Django 3.2.6 on 2021-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('number_of_lessons', models.IntegerField()),
                ('price_for_all', models.FloatField()),
            ],
        ),
    ]
