# Generated by Django 3.2.6 on 2021-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_lessonplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.DateTimeField()),
                ('lesson_status', models.BooleanField()),
            ],
        ),
    ]
