# Generated by Django 3.2.6 on 2021-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
