# Generated by Django 3.2.6 on 2021-08-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0005_auto_20210823_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('lesson_status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='lessons',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
